FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY src/db/prisma ./prisma

RUN npm ci

COPY . .

RUN npm run build
RUN npm run db:generate

FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --only=production

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src/generated ./dist/generated

CMD ["npm", "run", "worker"]
