// Octokit is the official GitHub REST API client
import { Octokit } from '@octokit/rest';
import { env } from '../config/env';

// Create an authenticated Octokit instance
const octokit = new Octokit({ auth: env.GITHUB_TOKEN });

/**
 * Fetch the raw unified diff of a pull request.
 */
export async function getPRDiff(owner: string, repo: string, pull_number: number) {
  const response = await octokit.rest.pulls.get({
    owner,
    repo,
    pull_number,
    // This custom media type returns the diff as plain text
    mediaType: { format: 'diff' },
  });
  // The response body is the diff string
  return response.data as unknown as string;
}

/**
 * Get the list of changed files in a PR (for future chunking or analysis).
 */
export async function getChangedFiles(owner: string, repo: string, pull_number: number) {
  const response = await octokit.rest.pulls.listFiles({
    owner,
    repo,
    pull_number,
  });
  return response.data;
}

/**
 * Post a "Pull Request Review" with line‑specific comments.
 * This is much better than a generic comment because each suggestion
 * appears directly next to the code it refers to.
 */
export async function postReview(
  owner: string,
  repo: string,
  pull_number: number,
  suggestions: Array<{
    file: string;
    line: number;
    message: string;
    explanation: string;
    severity: string;
  }>
) {
  // Get the PR metadata to obtain the latest commit SHA (required for review)
  const { data: pr } = await octokit.rest.pulls.get({ owner, repo, pull_number });
  const commit_id = pr.head.sha;

  // Map each AI suggestion to a GitHub review comment
  const comments = suggestions.map((s) => ({
    path: s.file,                         // which file
    commit_id,                            // must reference the head commit
    line: s.line,                         // line number
    // Format the body with severity and explanation
    body: `**[${s.severity.toUpperCase()}] ${s.message}**\n\n${s.explanation}`,
    side: 'RIGHT' as const,               // comment on the new version of the file
  }));

  // Create the review on the PR (all comments posted together)
  await octokit.rest.pulls.createReview({
    owner,
    repo,
    pull_number,
    commit_id,
    event: 'COMMENT',                     // a normal comment, not an approval/change request
    body: `## 🤖 AI Code Review\n\n_Review generated by AI. Visit the dashboard to provide feedback on suggestions._`,
    comments,
  });
}